<?php

namespace App\Exports;
use App\Models\tareasClaro;

use Maatwebsite\Excel\Concerns\FromCollection;

class TareasClaroExport implements FromCollection
{
    /**
    * @return \Illuminate\Support\Collection
    */
    public function collection()
    {
        $results = tareasClaro::all();

        $data []= [
            'Internal_ID'     => 'Internal_ID',
            'Nombre' => 'Nombre',
            'Proyecto'    => 'Proyecto',
	        'PartnerBU'  => 'PartnerBU',
            'Phone'     => 'Phone',
            'Sales_Order'     => 'Sales_Order',
            'WC_Findings'     => 'WC_Findings',
            'Materials'     => 'Materials',
            'Ecommerce_Client_consent'     => 'Ecommerce_Client_consent',
            'Associated_SKU'     => 'Associated_SKU',
            'Resource_Allocated'     => 'Resource_Allocated',
            'Supervisor_Asignado'     => 'Supervisor_Asignado',
            'GoDaddy_Giro_Empresa_Texto'     => 'GoDaddy_Giro_Empresa_Texto',
            'GoDaddy_Nombre_Comercial_Texto'     => 'GoDaddy_Nombre_Comercial_Texto',
            'A_que_sector_va_dirigido_su_sitio_web'     => 'A_que_sector_va_dirigido_su_sitio_web',
            'GoDaddy_item_mas_Vendido_Texto'     => 'GoDaddy_item_mas_Vendido_Texto',
            'GoDaddy_item_mas_Importante_Texto'     => 'GoDaddy_item_mas_Importante_Texto',
            'GoDaddy_Experiencia_Texto'     => 'GoDaddy_Experiencia_Texto',
            'GoDaddy_About_Opcional_Texto'     => 'GoDaddy_About_Opcional_Texto',
            'GoDaddy_Slogan_Basic_Texto'     => 'GoDaddy_Slogan_Basic_Texto',
            'GoDaddy_Promo_Basic_Texto'     => 'GoDaddy_Promo_Basic_Texto',
            'GoDaddy_Frase_Standard_Texto'     => 'GoDaddy_Frase_Standard_Texto',
            'GoDaddy_Testimonial_Standard_Texto'     => 'GoDaddy_Testimonial_Standard_Texto',
            'GoDaddy_Slogan_Basic_Texto2'     => 'GoDaddy_Slogan_Basic_Texto2',
            'GoDaddy_Promo_Standard_Texto'     => 'GoDaddy_Promo_Standard_Texto',
            'GoDaddy_Frase_Standard_Texto2'     => 'GoDaddy_Frase_Standard_Texto2',
            'GoDaddy_Equipo_Texto'     => 'GoDaddy_Equipo_Texto',
            'GoDaddy_Calle'     => 'GoDaddy_Calle',
            'GoDaddy_Num_Ext'     => 'GoDaddy_Num_Ext',
            'GoDaddy_Num_Int'     => 'GoDaddy_Num_Int',
            'GoDaddy_Colonia'     => 'GoDaddy_Colonia',
            'GoDaddy_Ciudad'     => 'GoDaddy_Ciudad',
            'GoDaddy_Pais'     => 'GoDaddy_Pais',
            'GoDaddy_Estado'     => 'GoDaddy_Estado',
            'GoDaddy_Codigo_Postal'     => 'GoDaddy_Codigo_Postal',
            'GoDaddy_Mapa_de_Sitio'     => 'GoDaddy_Mapa_de_Sitio',
            'GoDaddy_Aviso_de_Privacidad'     => 'GoDaddy_Aviso_de_Privacidad',
            'GoDaddy_Horarios_Abierto_Texto'     => 'GoDaddy_Horarios_Abierto_Texto',
            'GoDaddy_Notas_adicionales_para_direcciones'     => 'GoDaddy_Notas_adicionales_para_direcciones',
            'GoDaddy_Telefono_1'     => 'GoDaddy_Telefono_1',
            'GoDaddy_Telefono_2'     => 'GoDaddy_Telefono_2',
            'GoDaddy_Telefono_3'     => 'GoDaddy_Telefono_3',
            'GoDaddy_Notas_adicionales_para_telefono'     => 'GoDaddy_Notas_adicionales_para_telefono',
            'GoDaddy_Email_Contacto_Direccion'     => 'GoDaddy_Email_Contacto_Direccion',
            'GoDaddy_Efectivo'     => 'GoDaddy_Efectivo',
            'GoDaddy_Cheque'     => 'GoDaddy_Cheque',
            'GoDaddy_Visa'     => 'GoDaddy_Visa',
            'GoDaddy_MasterCard'     => 'GoDaddy_MasterCard',
            'GoDAddy_American_Express'     => 'GoDAddy_American_Express',
            'GoDaddy_Transferencia_Electronica'     => 'GoDaddy_Transferencia_Electronica',
            'Godaddy_Otras_formas_de_Pago'     => 'Godaddy_Otras_formas_de_Pago',
            'GoDaddy_Drive'     => 'GoDaddy_Drive',
            'GoDaddy_Redes_Sociales'     => 'GoDaddy_Redes_Sociales',
            'GoDaddy_Instrucciones_Adicionales_Texto'     => 'GoDaddy_Instrucciones_Adicionales_Texto',
            'GoDaddy_Materiales_Adicionales_Texto'     => 'GoDaddy_Materiales_Adicionales_Texto',
            'GoDaddy_E-commerce_Negocio'     => 'GoDaddy_E-commerce_Negocio',
            'GoDaddy_E-commerce_Historia'     => 'GoDaddy_E-commerce_Historia',
            'GoDaddy_E-commerce_Decision_Emprender'     => 'GoDaddy_E-commerce_Decision_Emprender',
            'GoDaddy_E-commerce_Expectativa_Cliente'     => 'GoDaddy_E-commerce_Expectativa_Cliente',
            'GoDaddy_E-commerce_Interes_Cliente'     => 'GoDaddy_E-commerce_Interes_Cliente',
            'GoDaddy_Ecommerce_Giro_Empresa_Texto"'     => 'GoDaddy_Ecommerce_Giro_Empresa_Texto"',
            'GoDaddy_Ecommerce_Nombre_Comercial_Texto'     => 'GoDaddy_Ecommerce_Nombre_Comercial_Texto',
            'GoDaddy_Ecommerce_Experiencia_Texto'     => 'GoDaddy_Ecommerce_Experiencia_Texto',
            'GoDaddy_Ecommerce_Frase_Texto'     => 'GoDaddy_Ecommerce_Frase_Texto',
            'GoDaddy_Blog_Titulo'     => 'GoDaddy_Blog_Titulo',
            'GoDaddy_Estilo_del_Indice'     => 'GoDaddy_Estilo_del_Indice',
            'GoDaddy_Estilo_del_Indice'     => 'GoDaddy_Estilo_del_Indice',
        ];

        foreach ($results as $row) {
            $data []= [
                'Internal_ID'   => $row->Internal_ID,
                'Nombre'        => $row->Nombre,
                'Proyecto'      => $row->Proyecto,
    	        'PartnerBU'     => $row->PartnerBU,
                'Phone'         => $row->Phone,
                'Sales_Order'   => $row->Sales_Order,
                'WC_Findings'   => $row->WC_Findings,
                'Materials'     => $row->Materials,
                'Ecommerce_Client_consent' => $row->Ecommerce_Client_consent,
                'Associated_SKU'           => $row->Associated_SKU,
                'Resource_Allocated'       => $row->Resource_Allocated,
                'Supervisor_Asignado'      => $row->Supervisor_Asignado,
                'GoDaddy_Giro_Empresa_Texto'            => $row->GoDaddy_Giro_Empresa_Texto,
                'GoDaddy_Nombre_Comercial_Texto'        => $row->GoDaddy_Nombre_Comercial_Texto,
                'A_que_sector_va_dirigido_su_sitio_web' => $row->A_que_sector_va_dirigido_su_sitio_web,
                'GoDaddy_item_mas_Vendido_Texto'        => $row->GoDaddy_item_mas_Vendido_Texto,
                'GoDaddy_item_mas_Importante_Texto'     => $row->GoDaddy_item_mas_Importante_Texto,
                'GoDaddy_Experiencia_Texto'       => $row->GoDaddy_Experiencia_Texto,
                'GoDaddy_About_Opcional_Texto'    => $row->GoDaddy_About_Opcional_Texto,
                'GoDaddy_Slogan_Basic_Texto'      => $row->GoDaddy_Slogan_Basic_Texto,
                'GoDaddy_Promo_Basic_Texto'       => $row->GoDaddy_Promo_Basic_Texto,
                'GoDaddy_Frase_Standard_Texto'    => $row->GoDaddy_Frase_Standard_Texto,
                'GoDaddy_Testimonial_Standard_Texto' => $row->GoDaddy_Testimonial_Standard_Texto,
                'GoDaddy_Slogan_Basic_Texto2'     => $row->GoDaddy_Slogan_Basic_Texto2,
                'GoDaddy_Promo_Standard_Texto'    => $row->GoDaddy_Promo_Standard_Texto,
                'GoDaddy_Frase_Standard_Texto2'   => $row->GoDaddy_Frase_Standard_Texto2,
                'GoDaddy_Equipo_Texto'  => $row->GoDaddy_Equipo_Texto,
                'GoDaddy_Calle'         => $row->GoDaddy_Calle,
                'GoDaddy_Num_Ext'       => $row->GoDaddy_Num_Ext,
                'GoDaddy_Num_Int'       => $row->GoDaddy_Num_Int,
                'GoDaddy_Colonia'       => $row->GoDaddy_Colonia,
                'GoDaddy_Ciudad'        => $row->GoDaddy_Ciudad,
                'GoDaddy_Pais'          => $row->GoDaddy_Pais,
                'GoDaddy_Estado'        => $row->GoDaddy_Estado,
                'GoDaddy_Codigo_Postal'  => $row->GoDaddy_Codigo_Postal,
                'GoDaddy_Mapa_de_Sitio'  => $row->GoDaddy_Mapa_de_Sitio,
                'GoDaddy_Aviso_de_Privacidad'    => $row->GoDaddy_Aviso_de_Privacidad,
                'GoDaddy_Horarios_Abierto_Texto' => $row->GoDaddy_Horarios_Abierto_Texto,
                'GoDaddy_Notas_adicionales_para_direcciones' => $row->GoDaddy_Notas_adicionales_para_direcciones,
                'GoDaddy_Telefono_1'     => $row->GoDaddy_Telefono_1,
                'GoDaddy_Telefono_2'     => $row->GoDaddy_Telefono_2,
                'GoDaddy_Telefono_3'     => $row->GoDaddy_Telefono_3,
                'GoDaddy_Notas_adicionales_para_telefono' => $row->GoDaddy_Notas_adicionales_para_telefono,
                'GoDaddy_Email_Contacto_Direccion'        => $row->GoDaddy_Email_Contacto_Direccion,
                'GoDaddy_Efectivo'   => $row->GoDaddy_Efectivo,
                'GoDaddy_Cheque'     => $row->GoDaddy_Cheque,
                'GoDaddy_Visa'       => $row->GoDaddy_Visa,
                'GoDaddy_MasterCard' => $row->GoDaddy_MasterCard,
                'GoDAddy_American_Express'          => $row->GoDAddy_American_Express,
                'GoDaddy_Transferencia_Electronica' => $row->GoDaddy_Transferencia_Electronica,
                'Godaddy_Otras_formas_de_Pago'      => $row->Godaddy_Otras_formas_de_Pago,
                'GoDaddy_Drive'          => $row->GoDaddy_Drive,
                'GoDaddy_Redes_Sociales' => $row->GoDaddy_Redes_Sociales,
                'GoDaddy_Instrucciones_Adicionales_Texto'  => $row->GoDaddy_Instrucciones_Adicionales_Texto,
                'GoDaddy_Materiales_Adicionales_Texto'     => $row->GoDaddy_Materiales_Adicionales_Texto,
                'GoDaddy_E-commerce_Negocio'     => $row->GoDaddy_Materiales_Adicionales_Texto,
                'GoDaddy_E-commerce_Historia'    => $row->GoDaddy_Materiales_Adicionales_Texto,
                'GoDaddy_E-commerce_Decision_Emprender'  => $row->GoDaddy_Materiales_Adicionales_Texto,
                'GoDaddy_E-commerce_Expectativa_Cliente' => $row->GoDaddy_Materiales_Adicionales_Texto,
                'GoDaddy_E-commerce_Interes_Cliente'     => $row->GoDaddy_Materiales_Adicionales_Texto,
                'GoDaddy_Ecommerce_Giro_Empresa_Texto'  => $row->GoDaddy_Ecommerce_Giro_Empresa_Texto,
                'GoDaddy_Ecommerce_Nombre_Comercial_Texto'=> $row->GoDaddy_Ecommerce_Nombre_Comercial_Texto,
                'GoDaddy_Ecommerce_Experiencia_Texto'     => $row->GoDaddy_Ecommerce_Experiencia_Texto,
                'GoDaddy_Ecommerce_Frase_Texto' => $row->GoDaddy_Ecommerce_Frase_Texto,
                'GoDaddy_Blog_Titulo'           => $row->GoDaddy_Blog_Titulo,
                'GoDaddy_Estilo_del_Indice'     => $row->GoDaddy_Estilo_del_Indice,
                'GoDaddy_Estilo_del_Indice'     => $row->GoDaddy_Estilo_del_Indice,
            ];
        }


        return $collection = collect($data);
    }
}
